data:
  dataset_name : "Liver_Lung"
  liver_image_dir: "/data/hyungseok/MSD_liver/imagesTr"
  liver_label_dir: "/data/hyungseok/MSD_liver/processed_labels"
  lung_image_dir: "/data/hyungseok/MSD_lung/imagesTr"
  lung_label_dir: "/data/hyungseok/MSD_lung/labelsTr"
  liver_train_image_txt : "/data/hyungseok/Swin-UNETR/notebook/tempp/liver.txt"
  liver_val_image_txt :  "/data/hyungseok/Swin-UNETR/notebook/tempp/liver_val.txt"
  lung_train_image_txt : "/data/hyungseok/Swin-UNETR/notebook/tempp/lung.txt"
  lung_val_image_txt : "/data/hyungseok/Swin-UNETR/notebook/tempp/lung_val.txt"
  liver_test_image_txt : "/data/hyungseok/Swin-UNETR/notebook/tempp/liver_test.txt"
  lung_test_image_txt : "/data/hyungseok/Swin-UNETR/notebook/tempp/lung_test.txt"
  save_dir: "/data/hyungseok/Swin-UNETR/Experiments/Models"
  log_dir : "/data/hyungseok/Swin-UNETR/Experiments/Logs"
  weights_path: "/data/hyungseok/Swin-UNETR/model_swinvit.pt"

transforms:
  num_samples: 4
  spacing : [1.0, 1.0, 1.0]
  liver:
    a_min : -21
    a_max : 189
    RandCropByPosNegLabeld_params:
      pos : 1
      neg : 1
    rand_flip_prob : 0.2
    rand_rotate_prob : 0.3
    rand_scale_intensity_factor : 0.1
    rand_scale_intensity_prob : 0.1
    rand_shift_intensity_offset : 0.1
    rand_shift_intensity_prob : 0.1
  lung:
    a_min : -1000
    a_max : 1000
    RandCropByPosNegLabeld_params:
      pos : 2
      neg : 1
    rand_flip_prob : 0.5
    rand_rotate_prob : 0.3
    rand_scale_intensity_factor : 0.1
    rand_scale_intensity_prob : 0.1
    rand_shift_intensity_offset : 0.1
    rand_shift_intensity_prob : 0.1

train_params:
  batch_size: 1                    # 배치 사이즈         #### NAME
  val_batch_size: 1                    # 배치 사이즈
  num_workers : 8
  val_num_workers : 4
  pin_memory : True
  max_epoch: 2000             # 최대 반복 횟수
  eval_epoch: 25                     # 검증 주기
  save_epoch: 50                     # 저장 주기
  seed: 1234                        # 랜덤 시드
  spatial_size: [64, 64, 64]          # 이미지 패치 크기         #### NAME
  num_samples: 4                    # 샘플 수 (데이터 증강 시)
  loss_type: "DiceCELoss"           # 손실 함수 종류         #### NAME
  optim_type: "AdamW"               # 옵티마이저 종류
  learning_rate: 1e-4               # 학습률                #### NAME
  weight_decay: 1e-5
  warmup : 100
  resume : False
  resume_path : ""
  lambda_contrast : 0.05
  use_contrastive_loss : False


test_params : 
  ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Post_Liver_Lung-lr1e-4-bs1-lossDiceCELoss+Cont1-patch64x64x64/2025-04-27_15-53/best_metric_model.pth"
  detr : "/data/hyungseok/Swin-UNETR/scripts/modelweight/detr/best_metric_model.pth"
  att_0313 : "/data/hyungseok/Swin-UNETR/scripts/modelweight/att/best_metric_model.pth"
  lung : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Lung-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2025-04-02_20-39/best_metric_model.pth"
  liver : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2025-04-02_17-55/best_metric_model.pth"
  base : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-DEBUG_Liver_Lung-lr1e-4-bs3-lossDiceCELoss-patch64x64x64/2025-04-01_16-26/best_metric_model.pth"
  base_iter : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-DEBUG_Liver_Lung-lr1e-4-bs3-lossDiceCELoss-patch64x64x64/2025-03-31_22-59/best_metric_model.pth"
  focal : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Post_Liver_Lung-lr1e-4-bs6-lossDiceFocalLoss-patch64x64x64/2025-03-25_11-47/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/BalancedContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs1-lossDiceCELoss+Cont1-patch64x64x64/2025-02-07_13-31/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2025-01-20_20-36/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Lung-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2025-01-17_20-52/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/results/local/md_cont1_2000/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr4e-4-bs3-lossDiceCELoss+Cont1-patch64x64x64/2024-12-18_11-08/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver_Lung-lr4e-4-bs6-lossDiceCELoss-patch64x64x64/2024-12-16_15-09/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver_Lung-lr4e-4-bs6-lossDiceCELoss-patch64x64x64/2024-12-16_15-06/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr4e-4-bs3-lossDiceCELoss-patch64x64x64/2024-12-13_15-51/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr1e-4-bs3-lossDiceCELoss+Cont3-patch64x64x64/2024-12-04_11-12/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr1e-4-bs3-lossDiceCELoss+Cont3-patch64x64x64/2024-12-09_16-08/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs3-lossDiceCELoss+Cont3-patch64x64x64/2024-12-03_02-53/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2024-12-02_14-27/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Lung-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2024-10-22_17-29/best_metric_model.pth"
  # "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_segheadsp-Liver_Lung-lr8e-4-bs3-lossDiceCELoss+Cont3-patch64x64x64/2024-11-28_13-29/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs3-lossDiceCELoss+Cont1-patch64x64x64/2024-11-18_20-20/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs6-lossDiceCELoss+Cont3-patch64x64x64/2024-11-07_14-59/best_metric_model.pth"
  # ckpt_dir : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs12-lossDiceCELoss+Cont1-patch64x64x64/2024-10-24_15-18/best_metric_model.pth"            

past :
  liver : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2024-10-24_15-44/best_metric_model.pth"
  lung : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Lung-lr1e-4-bs6-lossDiceCELoss-patch64x64x64/2024-10-22_17-29/best_metric_model.pth"
  base_line : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver_Lung-lr1e-4-bs8-lossDiceCELoss-patch64x64x64/2024-10-17_15-51/best_metric_model.pth"
  cont1 : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs6-lossDiceCELoss+Cont3-patch64x64x64/2024-10-17_15-52/best_metric_model.pth"
  cont3 : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung_md3-lr1e-4-bs6-lossDiceCELoss+Cont3-patch64x64x64/2024-10-17_20-16/best_metric_model.pth"
  cont2 : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs6-lossDiceCELoss+Cont2-patch64x64x64/2024-10-19_16-35/best_metric_model.pth"
  label3 : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr-Liver_Lung-lr1e-4-bs3-lossDiceCELoss-patch64x64x64/2024-11-12_15-09/best_metric_model.pth"
  label3cont3 : "/data/hyungseok/Swin-UNETR/Experiments/Models/ContrastiveSwinUNETR-Liver_Lung-lr1e-4-bs3-lossDiceCELoss+Cont1-patch64x64x64/2024-11-19_13-29/checkpoint_epoch.pth"
  label3seghead : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_segheadsp-Liver_Lung-lr1e-4-bs3-lossDiceCELoss-patch64x64x64/2024-11-19_13-30/best_metric_model.pth"
  mdconcat : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr8e-4-bs3-lossDiceCELoss-patch64x64x64/2024-11-23_13-47/best_metric_model.pth"
  label3mdconcat : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr8e-4-bs3-lossDiceCELoss-patch64x64x64/2024-11-23_13-45/best_metric_model.pth"
  label3md : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr4e-4-bs3-lossDiceCELoss-patch64x64x64/2024-12-13_15-45/best_metric_model.pth"
  label2md : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr4e-4-bs3-lossDiceCELoss-patch64x64x64/2024-12-13_15-51/best_metric_model.pth"
  t-sne_path : "/data/hyungseok/Swin-UNETR/Experiments/Models/SwinUnetr_multi_decoder-Liver_Lung-lr4e-4-bs3-lossDiceCELoss+Cont1-patch64x64x64/2024-12-18_11-08/best_metric_model.pth"
  
model_params:
  type : "SwinUnetr"
  # "SwinUnetr"
  # "BalancedContrastiveSwinUNETR"
  # "SwinUnetr_multi_decoder"
  img_size: [64, 64, 64]            # 입력 이미지 크기
  in_channels: 1                    # 입력 채널 수
  out_channels: 2                   # 출력 채널 수
  feature_size: 48                  # 피처 크기
  use_checkpoint: true              # 체크포인트 사용 여부

wandb:
  project_name: "Medseg_train"      # WandB 프로젝트 이름
  experiment_name: "Swin_UNETR_exp" # wandb run 이름
  group: "Swin_UNETR"               # WandB 그룹
  mode: "offline"                    # WandB 모드 (online, offline, disabled)
  log_code: true                    # 코드 저장 여부 (소스 파일)
  sync_tensorboard: False            # TensorBoard와 동기화 여부

accelerator_params:
  gradient_accumulation_steps: 1
  mixed_precision: "fp16"           # 혼합 정밀도 학습 설정
  log_with: ["wandb", "tensorboard"]  # 로그 툴 설정
  kwargs_handlers: True

cuda:
  CUDA_VISIBLE_DEVICES: [4]   # 사용할 GPU 설정
  benchmark: False
  deterministic: true